### ISSUE TITLE
Out of docker on raspberry pi zero

### ISSUE THREAD

**Issue by corrpel** [winterscar/GoogleAssistantWebserver#1]
Hello,
Can this be used on a RPI Zero without docker?
Thank you.

**Comment by winterscar** [comment]
Yeah, of course. Follow the instructions [here](https://developers.google.com/assistant/sdk/guides/library/python/embed/setup) for installation, and then run the hotword_webserver.py file in the same venv. 

This docker image is literally just an adaptation of those instructions for docker.

**Comment by corrpel** [comment]
Great! Thank you very much!
